name: AntiAFKPro
version: 1.1.0
description: An advanced AntiAFK Plugin
main: me.jet315.antiafkpro.AntiAFKPro
commands:
  antiafkpro:
    description: The base command for the AntiAFK Plugin
    aliases: [playtime]